### PR TITLE
Use ESLint on export to see if it might be invalid

### LINKED ISSUE #1787: Report of broken export relating to Global Object Identification
> When I do what you suggested it works exactly as I would have hoped. But then the exported schema breaks because it still references the removed field in a query extension:
> 
> ```js
> const Query_node_extensions = Object.assign(Object.create(null), {
>   grafast: {
>     plan(_$root, args) {
>       return node(nodeIdHandlerByTypeName, args.get("id"));
>     }
>   }
> });
> ```
> 
> Stack trace:
> 
> ```shell
> @spear-ai/underway-app:dev: [next:dev]  ⨯ ReferenceError: Cannot access 'nodeIdHandlerByTypeName' before initialization
> @spear-ai/underway-app:dev: [next:dev]     at eval (webpack-internal:///(rsc)/./src/app/api/_postgraphile/exported-schema.mjs:1320:16)
> @spear-ai/underway-app:dev: [next:dev]     at (rsc)/./src/app/api/_postgraphile/exported-schema.mjs (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/_rsc_src_app_api__postgraphile_exported-schema_mjs.js:20:1)
> @spear-ai/underway-app:dev: [next:dev]     at Function.__webpack_require__ (/Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/.next/server/webpack-runtime.js:33:43)
> @spear-ai/underway-app:dev: [next:dev]     at async getGraphQLResponse (webpack-internal:///(rsc)/./src/app/api/_postgraphile/graphql.ts:32:24)
> @spear-ai/underway-app:dev: [next:dev]     at async /Users/dtorres/Work/dev/spear-ai/underway/packages/underway-app/node_modules/@sentry/nextjs/cjs/common/wrapRouteHandlerWithSentry.js:50:32
> @spear-ai/underway-app:dev: [next:dev]  ✓ Compiled in 664ms (1404 modules)
> ```

See https://github.com/graphile/crystal/issues/1786#issuecomment-1747745176

Reported by @psirenny

### LINKED ISSUE #1938: graphile-export: automatically check (lint) for "use before initialized", if possible
Need to catch that class of bug. Maybe even a warning rather than an error.

### PR DESCRIPTION
**Pull request by benjie**
## Description

Specifically we're looking to catch situations where we use variables before they're defined (aka Temporal Dead Zone (TDZ)); however we know that GraphQL types often references each other (`Author` has many `Post`s, `Post` has `Author`), so the linting is limited to the current scope only. We'll only run these extra checks if ESLint is available.

:rotating_light: This will spot more invalid exports, so yet more people might get errors when exporting if there are bugs.

- Fixes #1787
- Fixes #1938

## Performance impact

Export of a schema takes longer due to linting.

## Security impact

None known.

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [ ] ~~I've added tests for the new feature, and `yarn test` passes.~~ Covered by existing tests.
- [ ] ~~I have detailed the new feature in the relevant documentation.~~
- [x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [x] If this is a breaking change I've explained why.

### CODE REVIEW

File: graphile-build/graphile-build/src/plugins/NodeIdCodecBase64JSONPlugin.ts [hunk 1]
```diff
@@ -19,11 +19,17 @@ export const NodeIdCodecBase64JSONPlugin: GraphileConfig.Plugin = {
...
+        build.registerNodeIdCodec(
+          EXPORTABLE(
+            (base64JSONDecode, base64JSONEncode) => ({
+              name: "base64JSON",
+              encode: base64JSONEncode,
+              decode: base64JSONDecode,
+            }),
+            [base64JSONDecode, base64JSONEncode],
+          ),
+        );
```
Comment (benjie) [inline graphile-build/graphile-build/src/plugins/NodeIdCodecBase64JSONPlugin.ts:32]: This fixes #1787
