### PR TITLE
Fix bug in relational polymorphism where the polymorphic relations were nonsensically added to concrete types

### LINKED ISSUE #2085: Derived types include selector for the derived types when using relational polymorphism
Consider a setup like this:

```sql
DROP SCHEMA if EXISTS "dansdata" cascade;

CREATE SCHEMA "dansdata";

CREATE TYPE dansdata.profile_type AS ENUM('individual', 'organization');

CREATE TABLE dansdata.profiles (
  id UUID DEFAULT gen_random_uuid () PRIMARY KEY,
  type dansdata.profile_type NOT NULL,
  name TEXT NOT NULL
);

comment ON TABLE dansdata.profiles IS $$
  @interface mode:relational type:type
  @type individual references:individuals
  @type organization references:organizations
  @name Profile

  Represents an entity with profile data.
$$;

CREATE TABLE dansdata.individuals (
  id UUID PRIMARY KEY REFERENCES dansdata.profiles (id) ON DELETE cascade
);

comment ON TABLE dansdata.individuals IS $$
  @name Individual

  Represents an individual person.
$$;

CREATE
OR REPLACE function dansdata.create_individual (name TEXT) returns dansdata.individuals AS $$
  WITH "profile" AS (
    INSERT INTO dansdata.profiles("type", "name") VALUES ('individual', name) RETURNING *
  ) INSERT INTO dansdata.individuals("id") (SELECT id from "profile") RETURNING *;
$$ language sql volatile strict security invoker;

CREATE TABLE dansdata.organizations (
  id UUID PRIMARY KEY REFERENCES dansdata.profiles (id) ON DELETE cascade
);

comment ON TABLE dansdata.organizations IS $$
  @name Organization

  Represents an organization.
$$;

CREATE
OR REPLACE function dansdata.create_organization (name TEXT) returns dansdata.organizations AS $$
  WITH "profile" AS (
    INSERT INTO dansdata.profiles("type", "name") VALUES ('organization', name) RETURNING *
  ) INSERT INTO dansdata.organizations("id") (SELECT id from "profile") RETURNING *;
$$ language sql volatile strict security invoker;
```

Based on the above setup, it is clear that each profile may be associated with only one of the `individual` or `organization` types. However, I am still able to write queries like this:

```gql
query {
  individuals {
    nodes {
      id
      type
      name
      # Why am I able to query for individual in here?
      individual {
        id
        type
        name
      }
      # Why am I able to query for organization in here?
      organization {
        id
        type
        name
      }
    }
  }
}
```

### Expected results

I should be able to do this:

```gql
query {
  individuals {
    nodes {
      id
      type
      name
    }
  }
}
```

### Actual results

I should not be able to do this:

```gql
query {
  individuals {
    nodes {
      id
      type
      name
      # Why am I able to query for individual in here?
      individual {
        id
        type
        name
      }
      # Why am I able to query for organization in here?
      organization {
        id
        type
        name
      }
    }
  }
}
```

### Additional context

PostgreSQL: docker - `postgis/postgis:16-3.4-alpine`
Node: v20.14.0
Postgraphile: 5.0.0-beta.26

### PR DESCRIPTION
**Pull request by benjie**
## Description

Fixes #2085

## Performance impact

Negligible.

## Security impact

Improvement?

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [x] I've added tests for the new feature, and `yarn test` passes.
- [ ] I have detailed the new feature in the relevant documentation.
- [x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [x] If this is a breaking change I've explained why.

### CODE REVIEW

File: graphile-build/graphile-build-pg/src/plugins/PgPolymorphismPlugin.ts [hunk 1]
```diff
@@ -588,6 +591,9 @@ export const PgPolymorphismPlugin: GraphileConfig.Plugin = {
               for (const [relationName, relationSpec] of Object.entries(
                 relations,
               )) {
+                // Skip over the polymorphic relations
+                if (polyRelationNames.includes(relationName)) continue;
```
Comment (benjie) [inline graphile-build/graphile-build-pg/src/plugins/PgPolymorphismPlugin.ts:595]: @FelixZY if you're interested; this was the fix.
