### PR TITLE
Fix double-encoding of queryValues in cursors

### LINKED ISSUE #1942: Unable to paginate if `orderBy` on boolean type field is combined with pagination parameters
### Summary

If a table exposes a boolean type field for ordering
```sql
create table locations (
  id uuid default gen_random_uuid() primary key,
  name text not null unique,
  is_public boolean not null default true
);

create index idx_is_public on locations (is_public);

```

then we can execute a query using the `orderBy: IS_PUBLIC_ASC` successfuly, but if we combine the `orderBy` with a pagination paramater `after`, then the query fails with the following error:

```
Masked GraphQL error (hash: 'rxMy2h8uOCdYdguPLy4fcLXMWOg', id: '6ACWFQYMDJ') Error: f isn't a boolean; cowardly refusing to cast it to postgres
    at Object.toPg (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/@dataplan/pg/dist/codecs.js:536:23)
    at /home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/@dataplan/pg/dist/steps/pgSelect.js:650:59
    at Array.map (<anonymous>)
    at /home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/@dataplan/pg/dist/steps/pgSelect.js:648:40
    at Array.map (<anonymous>)
    at PgSelectStep.execute (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/@dataplan/pg/dist/steps/pgSelect.js:643:93)
    at executeOrStream (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/grafast/dist/engine/executeBucket.js:446:25)
    at executeStep (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/grafast/dist/engine/executeBucket.js:569:19)
    at nextPhase (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/grafast/dist/engine/executeBucket.js:109:31)
    at next (/home/ruslik/.npm/_npx/e75fc4d1ace5dbd8/node_modules/grafast/dist/engine/executeBucket.js:154:20) {
  path: [ 'allLocations', 'nodes' ],
  locations: [ { line: 3, column: 5 } ],
  extensions: [Object: null prototype] {}
}

```

### Steps to reproduce

https://github.com/ervasive/graphile-has-prev-page/tree/order-by-boolean-field

### PR DESCRIPTION
**Pull request by benjie**
## Description

Fixes #1942; and probably some other issues!

## Performance impact

Marginal improvement.

## Security impact

None known.

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [x] I've added tests for the new feature, and `yarn test` passes.
- [ ] ~~I have detailed the new feature in the relevant documentation.~~
- [x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [ ] ~~If this is a breaking change I've explained why.~~

### CODE REVIEW

File: grafast/dataplan-pg/src/steps/pgSelect.ts [hunk 1]
```diff
@@ -1099,7 +1098,7 @@ export class PgSelectStep<
         getFragmentAndCodecFromOrder(this.alias, order, this.resource.codec);
       const { nulls, direction } = order;
       const sqlValue = this.placeholder(
-        toPg(access($parsedCursorPlan, [i + 1]), orderCodec),
+        access($parsedCursorPlan, [i + 1]),
```
Comment (benjie) [inline grafast/dataplan-pg/src/steps/pgSelect.ts:1101]: This is the actual fix; everything else is just testing noise.
